# Generated by Django 4.0 on 2023-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='num_available',
            field=models.IntegerField(default=1),
        ),
    ]
